Gaussian:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.5
    limits:
      lower: 0.0
      upper: inf
  centre:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 100.0
    width_modifier:
      type: Absolute
      value: 20.0
    limits:
      lower: -inf
      upper: inf
  normalization:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    limits:
      lower: 0.0
      upper: inf
