LinearFit:
  gradient:
    type: Uniform
    lower_limit: -10.0
    upper_limit: 10.0
  intercept:
    type: Uniform
    lower_limit: -10.0
    upper_limit: 10.0
PowerFit:
  gradient:
    type: Uniform
    lower_limit: -10.0
    upper_limit: 10.0
  intercept:
    type: Uniform
    lower_limit: -10.0
    upper_limit: 10.0
  power:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
